name: Django Testing CI

on: [ push, pull_request ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      ldap:
        image: ghcr.io/danyi1212/django-windowsauth:pr-6
        options: >-
          --health-cmd "nc localhost 636"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 389:389
          - 636:636

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10-dev"
        django-version:
          - "2.2"  # LTS
          - "3.1"
          - "3.2"  # LTS
        exclude:
          # Python 3.10 is compatible with Django 3.1+
          - python-version: "3.10-dev"
            django-version: "2.2"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m pip install -U pip

      - name: Install Dependencies
        working-directory: ./testproj
        run: |
          pip install -r requirements.txt

      - name: Upgrade django version
        run: |
          python -m pip uninstall -y django
          python -m pip install "Django~=${{ matrix.django-version }}.0"

      - name: Python and Django versions

        run: |
          echo "Python ${{ matrix.python-version }} -> Django ${{ matrix.django-version }}"
          python --version
          echo "Django: `django-admin --version`"

      - name: Run Tests
        working-directory: ./testproj
        run: |
          mkdir logs
          python manage.py test
